defaults:
  actions:
    backport:
      title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }}) by @{{ author }}"

queue_rules:
  - name: default
    queue_conditions:
      # Conditions to get out of the queue (= merged)
      - check-success~=/ Ready To Merge$

pull_request_rules:
  - name: Merge PRs that are ready
    conditions:
      - check-success~=/ Ready To Merge$
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - label!=status:block-merge
      - label=status:merge-when-green
    actions:
      queue:
        merge_method: merge
        update_method: rebase
        name: default

  - name: Merge (Rebase) PRs that are ready
    conditions:
      - check-success~=/ Ready To Merge$
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - label!=status:block-merge
      - label=status:merge-rebase-when-green
    actions:
      queue:
        merge_method: rebase
        update_method: rebase
        name: default

  - name: Merge (Squash) PRs that are ready
    conditions:
      - check-success~=/ Ready To Merge$
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - label!=status:block-merge
      - label=status:merge-squash-when-green
    actions:
      queue:
        merge_method: squash
        update_method: rebase
        name: default

  - name: Delete the PR branch and remove label after merge/close
    conditions:
      - or:
        - merged
        - closed
    actions:
      delete_head_branch: {}
      label:
        remove:
          - "status:merge-when-green"
          - "status:merge-rebase-when-green"
          - "status:merge-squash-when-green"

  - name: Labeling for Scala Steward PR's
    conditions:
      - author=scala-steward
    actions:
      label:
        add: [ "type:updates" ]
