name: Publish

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: false
        default: ''
      java:
        type: string
        required: false
        default: 11

jobs:
  cmd:
    name: JDK ${{ inputs.java }}
    runs-on: ubuntu-20.04
    if: ${{ github.event.repository.fork == false }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0
          ref: ${{ inputs.ref }}

      - name: Coursier Cache
        id: coursier-cache
        uses: coursier/cache-action@v6

      - name: Install Adoptium Temurin OpenJDK
        uses: coursier/setup-action@v1
        with:
          jvm: adoptium:${{ inputs.java }}

      - name: Publish artifacts
        run: sbt ci-release
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}

      - name: Cleanup before cache
        shell: bash
        run: |
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true
