name: Publish

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: false
        default: ''
      java:
        type: string
        required: false
        default: 17
      java-index:
        type: string
        required: false
        default: ''
      ignore-job-coursier-cache:
        type: boolean
        required: false
        default: true
      extra-coursier-cache-key:
        type: string
        required: false
        default: ''
      cmd:
        type: string
        required: false
        default: "sbt ci-release"
      gradle-build-root:
        type: string
        required: false
        default: ""

jobs:
  cmd:
    name: JDK ${{ inputs.java }}
    runs-on: ubuntu-24.04
    if: ${{ github.event.repository.fork == false }}
    steps:
      - name: Block deprecated repos in /etc/hosts
        run: |
          sudo echo "127.0.0.1 repo.scala-sbt.org" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 repo.typesafe.com" | sudo tee -a /etc/hosts
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0
          ref: ${{ inputs.ref }}

      - name: Coursier Cache
        id: coursier-cache
        uses: coursier/cache-action@v6
        with:
          ignoreJob: ${{ inputs.ignore-job-coursier-cache }}
          ignoreMatrix: true
          extraKey: ${{ inputs.extra-coursier-cache-key }}

      - name: Gradle Cache
        uses: burrunan/gradle-cache-action@v3
        with:
          build-root-directory: ${{ inputs.gradle-build-root }}
          # Disable caching of ~/.gradle/caches/build-cache-*
          save-local-build-cache: false
          # Disable caching of ~/.m2/repository/
          save-maven-dependencies-cache: false

      - name: Install Adoptium Temurin OpenJDK
        uses: coursier/setup-action@v1
        with:
          jvm: adoptium:${{ inputs.java }}
          jvm-index: ${{ inputs.java-index }}

      - name: Install sbt
        uses: sbt/setup-sbt@v1

      - name: Publish artifacts
        run: ${{ inputs.cmd }}
        env:
          # Credentials for publishing to Sonatype https://github.com/sbt/sbt-ci-release#secrets
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          # Keys for signing https://github.com/sbt/sbt-ci-release#secrets
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          # Gradle Plugin Portal API Keys https://docs.gradle.org/current/userguide/publishing_gradle_plugins.html
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}

      - name: Cleanup before cache
        shell: bash
        run: |
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true
